begin;
do $$
declare co uuid:=gen_random_uuid(); co2 uuid:=gen_random_uuid(); admin_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); resident_id uuid:=gen_random_uuid(); condo uuid:=gen_random_uuid(); secret_ref uuid; value jsonb; rev uuid;
begin
 insert into auth.users(id,email) values(admin_id,admin_id||'@example.invalid'),(staff_id,staff_id||'@example.invalid'),(resident_id,resident_id||'@example.invalid');
 insert into public.companies(id,name,label) values(co,'SMTP fixture','SMTP fixture'),(co2,'SMTP second fixture','SMTP second fixture');
 insert into public.company_members(company_id,user_id,role,status) values(co,admin_id,'admin','active'),(co,staff_id,'staff','active');
 insert into public.condominiums(id,company_id,name) values(condo,co,'SMTP fixture');
 insert into public.condominium_members(condominium_id,user_id,status) values(condo,resident_id,'active');
 perform set_config('request.jwt.claim.role','service_role',true);
 set local role service_role;
 perform public.company_smtp_secret(co,'{"host":"smtp.example.invalid","port":587,"user":"fixture","password":"FAKE-SMTP-TEST-ONLY","from":"fixture@example.invalid","replyTo":"fixture@example.invalid","name":"Fixture"}');
 if public.company_smtp_secret(co)->>'password'<>'FAKE-SMTP-TEST-ONLY' then raise exception 'Vault round-trip failed';end if;
 select secret_id,revision into secret_ref,rev from public.company_smtp where company_id=co;
 update public.company_smtp set verified_at=now() where company_id=co;
 perform public.company_smtp_secret(co,'{"host":"smtp.example.invalid","port":465,"user":"fixture","password":"","from":"fixture@example.invalid","replyTo":"fixture@example.invalid","name":"Updated"}');
 if public.company_smtp_secret(co)->>'password'<>'FAKE-SMTP-TEST-ONLY' then raise exception 'Blank password did not preserve secret';end if;
 if exists(select 1 from public.company_smtp where company_id=co and (verified_at is not null or revision=rev)) then raise exception 'Editing did not invalidate verification';end if;
 if public.company_smtp_secret(co2) is not null then raise exception 'Tenant isolation failure';end if;
 if public.resolve_auth_email_company(admin_id,admin_id||'@example.invalid')->>'platform'<>'true' then raise exception 'Admin sender wrong';end if;
 if public.resolve_auth_email_company(staff_id,staff_id||'@example.invalid')->>'company_id'<>co::text then raise exception 'Staff sender wrong';end if;
 if public.resolve_auth_email_company(resident_id,resident_id||'@example.invalid')->>'company_id'<>co::text then raise exception 'Resident sender wrong';end if;
 insert into public.company_members(company_id,user_id,role,status) values(co2,staff_id,'staff','active');
 if public.resolve_auth_email_company(staff_id,staff_id||'@example.invalid')->>'ambiguous'<>'true' then raise exception 'Ambiguous identity silently routed';end if;
 insert into public.auth_email_routes(email,company_id) values('invite-fixture@example.invalid',co);
 if public.resolve_auth_email_company(gen_random_uuid(),'invite-fixture@example.invalid')->>'company_id'<>co::text then raise exception 'New invite route wrong';end if;
 reset role;
 if exists(select 1 from vault.secrets where id=secret_ref and secret like '%FAKE-SMTP-TEST-ONLY%') then raise exception 'Stored plaintext';end if;
 perform set_config('request.jwt.claim.role','authenticated',true);
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 set local role authenticated;
 begin perform public.company_smtp_secret(co);raise exception 'Client can decrypt SMTP';exception when insufficient_privilege then null;end;
 begin perform secret_id from public.company_smtp;raise exception 'Client can read SMTP table';exception when insufficient_privilege then null;end;
 begin perform public.resolve_auth_email_company(staff_id,'fake@example.invalid');raise exception 'Client can resolve other accounts';exception when insufficient_privilege then null;end;
 reset role;
 delete from public.company_smtp where company_id=co;
 if exists(select 1 from vault.secrets where id=secret_ref) then raise exception 'Orphan credential';end if;
end $$;
select 'PASS: encrypted credentials, reset validation, preserve blank password, tenant routing, ambiguous account denied, no client access, cleanup' result;
rollback;
