begin;
do $$
declare sa uuid:=gen_random_uuid(); resident uuid:=gen_random_uuid(); co uuid:=gen_random_uuid(); condo uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); notice uuid:=gen_random_uuid(); n uuid; row_count integer; claimed uuid;
begin
 insert into auth.users(id,email) values(sa,sa||'@example.invalid'),(resident,resident||'@example.invalid');
 update public.profiles set is_super_admin=true where user_id=sa;
 insert into public.companies(id,name,label) values(co,'Email test','Email test');
 insert into public.condominiums(id,company_id,name) values(condo,co,'Email test');
 insert into public.condominium_members(condominium_id,user_id) values(condo,resident);
 perform set_config('request.jwt.claim.sub',sa::text,true);
 set local role authenticated;
 insert into public.assemblies(id,condominium_id,title,scheduled_for,location,agenda,status) values(a,condo,'Test assembly',now()+interval '1 day','Hall','Agenda','draft');
 reset role;
 if exists(select 1 from public.notifications where condominium_id=condo) then raise exception 'TEST FAILED draft email';end if;
 set local role authenticated;
 update public.assemblies set status='scheduled' where id=a;
 update public.assemblies set status='scheduled' where id=a;
 insert into public.notices(id,condominium_id,title,body) values(notice,condo,'Test notice','Content');
 reset role;
 select count(*) into row_count from public.notification_emails q join public.notifications n on n.id=q.notification_id where n.condominium_id=condo and n.user_id=resident;
 if row_count<>2 then raise exception 'TEST FAILED notification queue or dedup: %',row_count;end if;
 select id into n from public.notifications where condominium_id=condo limit 1;
 set local role service_role;
 if not public.can_receive_notification_email(n) then raise exception 'TEST FAILED recipient denied';end if;
 update public.email_dispatch_config set enabled=true where id=1;
 update public.notification_emails set next_attempt_at=now()+interval '1 day' where notification_id not in(select id from public.notifications where condominium_id=condo);
 if exists(select 1 from public.claim_notification_email()) then raise exception 'TEST FAILED unconfigured SMTP claimed';end if;
 insert into public.company_smtp(company_id,secret_id,verified_at) values(co,gen_random_uuid(),now());
 select notification_id into claimed from public.claim_notification_email();
 if claimed is null or not exists(select 1 from public.notification_emails where notification_id=claimed and status='sending' and attempts=1) then raise exception 'TEST FAILED atomic claim';end if;
 if exists(select 1 from public.claim_notification_email() where notification_id=claimed) then raise exception 'TEST FAILED duplicate claim';end if;
 reset role;
 update public.condominium_members set status='blocked' where condominium_id=condo;
 set local role service_role;
 if public.can_receive_notification_email(n) then raise exception 'TEST FAILED blocked recipient accepted';end if;
 reset role;
 perform set_config('request.jwt.claim.sub',resident::text,true);
 set local role authenticated;
 begin perform public.claim_notification_email();raise exception 'TEST FAILED user can dispatch';exception when insufficient_privilege then null;end;
 begin perform cron_secret from public.email_dispatch_config;raise exception 'TEST FAILED exposed secret';exception when insufficient_privilege then null;end;
 reset role;
end $$;
select 'PASS drafts excluded, resident events queued, no duplicates, recipient access rechecked, queue and secrets restricted' result;
rollback;
