begin;
do $$
declare co uuid:=gen_random_uuid(); co2 uuid:=gen_random_uuid(); condo uuid:=gen_random_uuid(); condo2 uuid:=gen_random_uuid(); adm uuid:=gen_random_uuid(); worker uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); team uuid; list uuid; job uuid; snapshot jsonb; resident uuid:=gen_random_uuid(); supplier uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email) values(adm,adm||'@example.invalid'),(worker,worker||'@example.invalid'),(outsider,outsider||'@example.invalid'),(resident,resident||'@example.invalid');
 insert into public.companies(id,name,label) values(co,'FSM fixture','FSM fixture'),(co2,'Other','Other');
 insert into public.company_members(company_id,user_id,role,status) values(co,adm,'admin','active'),(co,worker,'staff','active'),(co2,outsider,'admin','active');
 insert into public.company_admin_licenses(company_id,user_id,license_key,billing_cycle,starts_on,expires_on,status) values(co,adm,gen_random_uuid()::text,'monthly',current_date-1,current_date+31,'active');
 insert into public.condominiums(id,company_id,name) values(condo,co,'FSM condo'),(condo2,co2,'Other condo');
 insert into public.condominium_members(condominium_id,user_id) values(condo,resident);
 insert into public.suppliers(id,condominium_id,name) values(supplier,condo,'External cleaner');
 perform set_config('request.jwt.claim.sub',adm::text,true);set local role authenticated;
 perform public.fsm_api(co,'activate','{"enabled":true,"price":0}');
 perform public.fsm_api(co,'team',jsonb_build_object('name','Cleaners','specialty','Limpeza','leader_id',worker,'member_names','["Ana without account","João without account"]'::jsonb,'members',jsonb_build_array(worker,adm)));
 snapshot:=public.fsm_api(co,'read');team:=(snapshot->'teams'->0->>'id')::uuid;
 perform public.fsm_api(co,'checklist',jsonb_build_object('condominium_id',null,'name','Daily','items','["Clean entrance","Clean stairs"]'::jsonb));
 snapshot:=public.fsm_api(co,'read');list:=(snapshot->'checklists'->0->>'id')::uuid;
 perform public.fsm_api(co,'job',jsonb_build_object('condominium_id',condo,'team_id',team,'title','Cleaning','scheduled_for',now(),'checklists',jsonb_build_array(list)));
 snapshot:=public.fsm_api(co,'read');job:=(snapshot->'jobs'->0->>'id')::uuid;
 if snapshot->'jobs'->0->'team_snapshot'->'members'->>0<>'Ana without account' then raise exception 'Missing named members';end if;
 begin perform public.fsm_api(co,'team_delete',jsonb_build_object('id',team));raise exception 'Deleted pending team';exception when raise_exception then if sqlerrm='Deleted pending team' then raise;end if;end;
 begin perform public.manage_company_employee(co,worker,'delete');raise exception 'Deleted pending worker';exception when raise_exception then if sqlerrm='Deleted pending worker' then raise;end if;end;
 begin perform public.fsm_api(co,'start',jsonb_build_object('id',job));raise exception 'Non-leader started';exception when raise_exception then if sqlerrm='Non-leader started' then raise;end if;end;
 perform public.fsm_api(co,'checklist',jsonb_build_object('id',list,'condominium_id',condo,'name','New','items','["Changed"]'::jsonb));
 snapshot:=public.fsm_api(co,'read');if snapshot->'jobs'->0->'checklist'->0->>'task'<>'Clean entrance' then raise exception 'Snapshot changed';end if;
 begin perform public.fsm_api(co,'job',jsonb_build_object('condominium_id',condo2,'team_id',team,'title','Bad','scheduled_for',now(),'checklists','[]'::jsonb));raise exception 'Cross tenant allowed';exception when raise_exception then if sqlerrm='Cross tenant allowed' then raise;end if;end;
 begin perform public.fsm_api(co,'price','{"price":99}');raise exception 'Admin changed price';exception when insufficient_privilege then null;end;
 reset role;perform set_config('request.jwt.claim.sub',worker::text,true);set local role authenticated;
 begin perform public.fsm_api(co,'team',jsonb_build_object('name','Bad','specialty','Bad','members','[]'::jsonb));raise exception 'Worker managed team';exception when insufficient_privilege then null;end;
 if not public.fsm_leader_context() then raise exception 'Leader context missing';end if;
 perform public.fsm_api(co,'start',jsonb_build_object('id',job));
 reset role;update public.fsm_jobs set started_at=now()-interval '42 minutes' where id=job;set local role authenticated;
 perform public.fsm_api(co,'progress',jsonb_build_object('id',job,'worked_minutes',45,'report','','answers','[{"status":"done"},{"status":"not_done"}]'::jsonb));
 snapshot:=public.fsm_api(co,'read');if snapshot->'jobs'->0->'answers'->0->>'status'<>'done' or snapshot->'jobs'->0->>'status'<>'progress' then raise exception 'Progress not saved';end if;
 begin perform public.fsm_api(co,'finish',jsonb_build_object('id',job,'worked_minutes',30,'report','Finished','answers','[]'::jsonb));raise exception 'Incomplete accepted';exception when raise_exception then if sqlerrm='Incomplete accepted' then raise;end if;end;
 perform public.fsm_api(co,'finish',jsonb_build_object('id',job,'worked_minutes',90,'report','','answers','[{"status":"done","note":""},{"status":"not_done","note":""}]'::jsonb));
 snapshot:=public.fsm_api(co,'read');if (snapshot->'jobs'->0->>'worked_minutes')::integer<>42 or snapshot->'jobs'->0->>'status'<>'completed' or snapshot->'jobs'->0->>'started_at' is null then raise exception 'Completion failed';end if;
 begin perform public.fsm_api(co,'start',jsonb_build_object('id',job));raise exception 'Restart allowed';exception when raise_exception then if sqlerrm='Restart allowed' then raise;end if;end;
 reset role;perform set_config('request.jwt.claim.sub',resident::text,true);set local role authenticated;
 snapshot:=public.condominium_service_schedule(condo);
 if jsonb_array_length(snapshot)<>1 or (snapshot->0)-array['id','title','scheduled_for','status','service_performed']<>'{}'::jsonb then raise exception 'Resident private details leak';end if;
 begin perform public.fsm_api(co,'read');raise exception 'Resident FSM access';exception when insufficient_privilege then null;end;
 begin perform public.condominium_service_schedule(condo2);raise exception 'Resident other condo access';exception when insufficient_privilege then null;end;
 reset role;perform set_config('request.jwt.claim.sub',adm::text,true);set local role authenticated;
 perform public.fsm_api(co,'job',jsonb_build_object('condominium_id',condo,'provider_type','external','supplier_id',supplier,'title','External cleaning','scheduled_for',now(),'tasks','["Clean windows"]'::jsonb));
 snapshot:=public.fsm_api(co,'read');if (snapshot->>'total')::integer<>2 then raise exception 'External creation failed';end if;
 perform public.fsm_api(co,'team_delete',jsonb_build_object('id',team));
 perform public.manage_company_employee(co,worker,'edit','New local name','staff');
 if not exists(select 1 from public.list_company_users(co) where user_id=worker and full_name='New local name') then raise exception 'Employee edit failed';end if;
 perform public.manage_company_employee(co,worker,'delete');
 if exists(select 1 from public.list_company_users(co) where user_id=worker) then raise exception 'Employee removal failed';end if;
 reset role;
 if not exists(select 1 from auth.users where id=worker) then raise exception 'Auth identity deleted';end if;
 if not exists(select 1 from public.fsm_jobs where id=job and status='completed' and team_snapshot->'members'->>0='Ana without account') then raise exception 'History lost';end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);set local role authenticated;
 begin perform public.fsm_api(co,'read');raise exception 'Tenant read allowed';exception when insufficient_privilege then null;end;
 reset role;
end $$;
select 'PASS FSM isolation, resident privacy, named members, employee edit/removal, history, external provider, checklist snapshot, automatic duration and lifecycle' result;
rollback;
