begin;
do $$
declare co uuid:=gen_random_uuid(); condo uuid:=gen_random_uuid(); other_condo uuid:=gen_random_uuid(); adm uuid:=gen_random_uuid(); worker uuid:=gen_random_uuid(); resident uuid:=gen_random_uuid(); supplier uuid:=gen_random_uuid(); foreign_supplier uuid:=gen_random_uuid(); team uuid; sid uuid:=gen_random_uuid(); job uuid; next_job uuid; data jsonb; cfg jsonb; due date;
begin
 insert into auth.users(id,email) values(adm,adm||'@example.invalid'),(worker,worker||'@example.invalid'),(resident,resident||'@example.invalid');
 insert into public.companies(id,name,label) values(co,'Periodic fixture','Fixture');
 insert into public.company_members(company_id,user_id,role) values(co,adm,'admin'),(co,worker,'staff');
 insert into public.company_admin_licenses(company_id,user_id,license_key,billing_cycle,starts_on,expires_on,status) values(co,adm,gen_random_uuid()::text,'monthly',current_date-1,current_date+31,'active');
 insert into public.condominiums(id,company_id,name) values(condo,co,'Condo'),(other_condo,co,'Other condo');
 insert into public.condominium_members(condominium_id,user_id) values(condo,resident);
 insert into public.suppliers(id,condominium_id,name) values(supplier,condo,'External'),(foreign_supplier,other_condo,'Foreign');
 insert into public.periodic_services(id,condominium_id,title,frequency,next_service_on,time_of_day) values(sid,condo,'Limpeza','Semanal',current_date,'09:00');
 perform set_config('request.jwt.claim.sub',adm::text,true);set local role authenticated;
 perform public.fsm_api(co,'activate','{"enabled":true,"price":0}');
 perform public.fsm_api(co,'team',jsonb_build_object('name','Cleaners','specialty','Limpeza','leader_id',worker,'member_names','["Ana"]'::jsonb,'members',jsonb_build_array(worker)));
 data:=public.fsm_api(co,'read');team:=(data->'teams'->0->>'id')::uuid;
 cfg:=jsonb_build_object('service_id',sid,'provider_type','internal','team_id',team,'tasks','["Entrada","Escadas"]'::jsonb,'weekdays','[1,3,5]'::jsonb,'orders_enabled',true);
 data:=public.periodic_service_workflow(co,'save',cfg);job:=(data->>'job_id')::uuid;if job is null then raise exception 'Initial order not generated';end if;
 data:=public.periodic_service_workflow(co,'save',cfg);if (data->>'job_id')::uuid<>job then raise exception 'Duplicate on save';end if;
 data:=public.periodic_service_workflow(co,'read',jsonb_build_object('condominium_id',condo));
 if jsonb_array_length(data->'jobs')<>1 or data->'settings'->0->'tasks'->>0<>'Entrada' then raise exception 'Persistence failed';end if;
 reset role;select next_service_on into due from public.periodic_services where id=sid;if extract(isodow from due)::integer not in(1,3,5) then raise exception 'Initial weekday wrong';end if;
 perform set_config('request.jwt.claim.sub',worker::text,true);set local role authenticated;
 begin perform public.periodic_service_workflow(co,'read',jsonb_build_object('condominium_id',condo));raise exception 'Worker accessed settings';exception when insufficient_privilege then null;end;
 perform public.fsm_api(co,'start',jsonb_build_object('id',job));
 reset role;perform set_config('request.jwt.claim.sub',adm::text,true);set local role authenticated;
 perform public.periodic_service_workflow(co,'save',cfg||'{"tasks":["New future task"]}'::jsonb);
 data:=public.periodic_service_workflow(co,'read',jsonb_build_object('condominium_id',condo));if jsonb_array_length(data->'jobs'->0->'checklist')<>2 then raise exception 'Running checklist changed';end if;
 reset role;perform set_config('request.jwt.claim.sub',worker::text,true);set local role authenticated;
 perform public.fsm_api(co,'finish',jsonb_build_object('id',job,'service_performed',false,'answers','[{"status":"not_done"},{"status":"not_done"}]'::jsonb));
 reset role;
 if exists(select 1 from public.periodic_services where id=sid and last_service_on is not null) then raise exception 'Missed visit changed last performed date';end if;
 if not exists(select 1 from public.periodic_service_visits where periodic_service_id=sid and result='missed') then raise exception 'Missing not-done visit';end if;
 select id into next_job from public.fsm_jobs where service_id=sid and status='scheduled';if next_job is null or next_job=job then raise exception 'Next order missing';end if;
 if not exists(select 1 from public.fsm_jobs where id=next_job and checklist->0->>'task'='New future task' and scheduled_for::date>due) then raise exception 'Next order settings/date wrong';end if;
 perform set_config('request.jwt.claim.sub',adm::text,true);set local role authenticated;
 perform public.periodic_service_workflow(co,'toggle',jsonb_build_object('service_id',sid,'active',false));
 perform public.periodic_service_workflow(co,'toggle',jsonb_build_object('service_id',sid,'active',true));
 begin perform public.periodic_service_workflow(co,'save',cfg||jsonb_build_object('provider_type','external','supplier_id',foreign_supplier));raise exception 'Foreign supplier accepted';exception when raise_exception then if sqlerrm='Foreign supplier accepted' then raise;end if;end;
 perform public.periodic_service_workflow(co,'save',cfg||jsonb_build_object('provider_type','external','supplier_id',supplier));
 reset role;perform set_config('request.jwt.claim.sub',resident::text,true);set local role authenticated;
 begin perform public.periodic_service_workflow(co,'read',jsonb_build_object('condominium_id',condo));raise exception 'Resident settings leak';exception when insufficient_privilege then null;end;
 data:=public.condominium_service_schedule(condo);if exists(select 1 from jsonb_array_elements(data) x where x-array['id','title','scheduled_for','status','service_performed']<>'{}') then raise exception 'Resident details leak';end if;
 reset role;
 if private.next_periodic_day('2026-09-30','Mensal','{}')<>'2026-10-30'::date or private.next_periodic_day('2026-09-30','Pontual','{}') is not null then raise exception 'Calendar recurrence failed';end if;
end $$;
select 'PASS unified service: durable checklist, weekday scheduling, idempotent orders, immutable running work, automatic next order, not-done result, pause/reactivate, provider boundary, resident privacy' result;
rollback;
