import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const companyId='00000000-0000-0000-0000-000000000001';
const config={host:'smtp.example.invalid',port:587,user:'fixture@example.invalid',password:'FAKE-SECRET-FIXTURE',name:'Fixture',from:'fixture@example.invalid',replyTo:'reply@example.invalid'};
let handler,valid=true,role='admin',companyActive=true,locked=false,mailCount=0,lastMail,secretReads=0,fail=false;
const client={auth:{getUser:async()=>({data:{user:valid?{id:'admin',email:'admin@example.invalid'}:null},error:!valid})},rpc:async()=>{secretReads++;return {data:config}},from(table){let update;const q={select(){return q},eq(){return q},in(){return q},or(){return q},update(v){update=v;return q},then(resolve){resolve({count:0,error:null})},async maybeSingle(){return {data:table==='company_members'?role?{role}:null:table==='company_smtp'?update?.last_test_at&&locked?null:{verified_at:'fixture',revision:'fixture'}:null}},async single(){return {data:{name:'Fixture',status:companyActive?'active':'suspended'}}}};return q;}};
const source=stripTypeScriptTypes(readFileSync(new URL('../supabase/functions/company-email/index.ts',import.meta.url),'utf8').replace(/^import .*\n/gm,''));
vm.runInNewContext(source,{Response,Request,Date,Promise,createClient:()=>client,validateConfig:v=>v,companyTransport:async()=>({sendMail:async v=>{mailCount++;lastMail=v;if(fail)throw {code:'EAUTH',message:config.password};return {accepted:['admin@example.invalid']}},close(){}}),safeError:e=>({code:e.code}),emailLayout:()=>({text:'Fixture'}),appUrl:'https://test.invalid',Deno:{env:{get:()=> 'fixture'},serve:fn=>handler=fn}});
const request=(action,extra={})=>new Request('https://test.invalid',{method:'POST',headers:{Authorization:'Bearer fixture'},body:JSON.stringify({companyId,action,...extra})});
valid=false;assert.equal((await handler(request('get'))).status,401);assert.equal(secretReads,0);valid=true;
role='staff';assert.equal((await handler(request('get'))).status,403);assert.equal(secretReads,0);
role=null;assert.equal((await handler(request('save',{config}))).status,403);assert.equal(secretReads,0);
role='admin';let response=await handler(request('get'));assert.equal(response.status,200);const body=await response.text();assert.ok(!body.includes(config.password));assert.ok(body.includes('hasPassword'));
response=await handler(request('test',{to:'attacker@example.invalid'}));assert.equal(response.status,200);assert.equal(lastMail.to,'admin@example.invalid');assert.equal(lastMail.from.address,config.from);
locked=true;assert.equal((await handler(request('test'))).status,429);assert.equal(mailCount,1);locked=false;
fail=true;response=await handler(request('test'));assert.equal(response.status,502);assert.ok(!(await response.text()).includes(config.password));
companyActive=false;assert.equal((await handler(request('test'))).status,403);
console.log('PASS company SMTP endpoint: authenticated own administrator only; secret redacted; fixed test recipient; rate limit; safe errors; suspended company denied');
