import assert from 'node:assert/strict';
const memory=new Map();
globalThis.sessionStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
globalThis.location={href:'https://demo.example/demo.html',search:''};
const {supabase:db}=await import('../assets/js/demo-backend.js');
const companies=await db.from('condominiums').select();assert.equal(companies.data.length,3);
const charges=await db.from('fraction_charges').select().eq('condominium_id','c1');assert.equal(charges.data.length,24);
const reviewed=await db.rpc('review_payment_proof',{p_proof_id:'proof1',p_approve:true});assert.equal(reviewed.error,null);
const quota=await db.from('fraction_charges').select().eq('id','c1-f1-quota').single();assert.equal(quota.data.status,'paid');
assert.ok((await db.rpc('review_payment_proof',{p_proof_id:'proof1',p_approve:true})).error);
const newIssue=await db.from('issues').insert({condominium_id:'c1',title:'Portão'}).select().single();assert.equal(newIssue.data.status,'open');
await db.from('issues').update({status:'resolved'}).eq('id',newIssue.data.id);
assert.equal((await db.from('issues').select().eq('id',newIssue.data.id).single()).data.status,'resolved');
globalThis.location.search='?role=resident';
const {supabase:resident}=await import('../assets/js/demo-backend.js?resident-test');
assert.equal((await resident.from('fractions').select()).data.length,1);
assert.equal((await resident.from('fraction_charges').select()).data.length,1);
const vote={poll_id:'c1-poll',condominium_id:'c1',fraction_id:'c1-f1',choice:'yes'};
assert.equal((await resident.from('poll_votes').insert(vote)).error,null);
assert.ok((await resident.from('poll_votes').insert(vote)).error);
console.log('PASS: isolated demo data, actual CRUD, payment validation, resident filtering and one vote per fraction.');
