import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
let source=await readFile(new URL('../assets/js/reports.js',import.meta.url),'utf8');
source=source.replace(/^import .*;\n/gm,'');
const requests=[];
globalThis.reportTestClient={from(name){let offset=0,filter;return {select(){return this},eq(k,v){filter=[k,v];return this},order(){return this},range(a){offset=a;requests.push({name,offset,filter});return Promise.resolve({data:name==='documents'?(offset===0?Array.from({length:1000},(_,id)=>({id})):[{id:1000}]):[],error:null})}}}};
source='const supabase=globalThis.reportTestClient;const pollResults=async()=>[];const issueDisplayLabel=i=>i.status;\n'+source;
const {financialSummary,loadReport,reportMarkup}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const d=await loadReport('condo-1');
assert.equal(d.documents.length,1001);
assert(requests.every(r=>r.filter[1]==='condo-1'));
assert(requests.some(r=>r.name==='payment_allocations'&&r.filter[0]==='fraction_charges.condominium_id'));
assert(requests.some(r=>r.name==='obligation_checklist_items'&&r.filter[0]==='obligations.condominium_id'));
d.fractions=[{id:'f',code:'A'}];
d.fraction_charges=[{id:'c',fraction_id:'f',amount_due:100.10,due_date:'2026-01-01',status:'partial'},{id:'x',fraction_id:'f',amount_due:999,status:'cancelled'}];
d.fraction_payments=[{amount:50.05}];d.payment_allocations=[{charge_id:'c',amount:40.05}];
const total=financialSummary(d,'2026-09-25');
assert.deepEqual([total.charged,total.receipts,total.outstanding,total.overdue,total.unallocated],[10010,5005,6005,6005,1000]);
const html=reportMarkup({name:'<script>alert(1)</script>'},d);
assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));assert(html.includes('Assembleias'));assert(html.includes('Votações'));
globalThis.reportTestClient.from=()=>({select(){return this},eq(){return this},order(){return this},range(){return Promise.resolve({data:null,error:{message:'offline'}})}});
await assert.rejects(loadReport('condo-1'),/offline/);
delete globalThis.reportTestClient;
console.log('PASS: financial cents, cancelled charges, report scoping, pagination, safe markup and loading failure.');
