import {logoBase64} from './logo.js';
export const sender='geral.condomia@gmail.com';
export const appUrl='https://flavavisio.github.io/condominio/app.html';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function emailLayout(title,message,actionUrl=appUrl,actionLabel='Abrir aplicação',brand){
 if(!actionUrl.startsWith('https://flavavisio.github.io/condominio/'))throw new Error('Destino de email inválido');
 const brandName=escape(brand?.name||'Condomia'),contact=escape(brand?.email||sender);
 const logo=brand?.logo&&/^https:\/\//.test(brand.logo)?escape(brand.logo):'cid:condomia-logo';
 const tagline=brand?'Gestão de condomínios':'Condomínio fácil';
 const heading=escape(title),body=escape(message).replace(/\r?\n/g,'<br>');
 return {
 text:`${title}\n\n${message}\n\n${actionLabel}: ${actionUrl}\n\n${brand?.name||'Condomia'} — ${tagline}\n${brand?.email||sender}`,
 html:`<!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f3f6fa;font-family:Arial,Helvetica,sans-serif;color:#18354d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f6fa"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#ffffff;border:1px solid #e2e9f0;border-radius:16px"><tr><td style="padding:28px;background:#0b3152;border-radius:16px 16px 0 0"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td width="64"><img src="${logo}" width="56" height="56" alt="${brandName}" style="display:block;border:0;border-radius:12px"></td><td style="padding-left:12px"><div style="font-size:28px;font-weight:bold;letter-spacing:-1px;color:#ffffff">${brandName}</div><div style="padding-top:5px;font-size:13px;color:#b3d5e3">${tagline}</div></td></tr></table></td></tr><tr><td style="padding:30px 28px"><p style="margin:0 0 12px;font-size:11px;letter-spacing:1.5px;font-weight:bold;color:#137a8e">${brandName}</p><h1 style="margin:0 0 18px;font-size:23px;line-height:1.3;color:#0b3152">${heading}</h1><p style="margin:0 0 26px;font-size:15px;line-height:1.7;color:#465a6c">${body}</p><table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#137a8e" style="border-radius:8px"><a href="${escape(actionUrl)}" style="display:inline-block;padding:14px 22px;font-size:14px;font-weight:bold;text-decoration:none;color:#ffffff">${escape(actionLabel)}</a></td></tr></table><p style="margin:24px 0 0;font-size:12px;line-height:1.6;color:#778696">Se não reconhece esta mensagem, contacte ${brandName}.</p></td></tr><tr><td style="padding:20px 28px;border-top:1px solid #e6ebf2;font-size:12px;line-height:1.7;color:#718293"><strong style="color:#0b3152">${brandName} · ${tagline}</strong><br>Precisa de ajuda? Responda a este email.<br><a href="mailto:${contact}" style="color:#137a8e;text-decoration:none">${contact}</a></td></tr></table></td></tr></table></body></html>`,
 attachments:[{filename:'condomia.png',content:logoBase64,encoding:'base64',contentType:'image/png',cid:'condomia-logo',contentDisposition:'inline'}]
 };
}
